---
title: "Fast laps template"
output:
  md_document:
    variant: gfm
    
params:
  session: 'race'
  stub: 'generic'
  outdir: 'race'
  rootdir: './reports'
  year: 2018
  country: 'generic'
  results: NA
---
```{r setupFastlaps, include=FALSE,message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.path = paste0("images/f1_",year,"_",stub,"-"))
```

# Fast laps

```{r fl_init, echo=FALSE}
session = params$session
rootdir = params$rootdir
outdir = params$outdir
stub = params$stub
year = params$year
country = params$country
results = params$results


#results['code']=apply(results['driverId'],2,function(x) driverCodeMap(x))
resultstmp=plyr::rename(results, c("code"="DRIVER", "carNum"="CARNO.","grid"="GRID", 
                             "pos"="RANK", "status"="STATUS","laps"="LAPS"))
resultstmp['FASTLAP']=with(resultstmp, paste0(fastlapnum,': ',fastlaptime,' (',fastlaprank,')'))
resultstmp$FASTLAP[resultstmp$FASTLAP=='NA: NA (NA)']=''
kable(subset(resultstmp,select=c('RANK','CARNO.','DRIVER','GRID', 'STATUS', 'LAPS', 'FASTLAP')),
      format='markdown', row.names = FALSE)
```


```{r fl_percenttable}
tmp=subset(results[order(results$fastlaprank),], select=c('code','fastlaptime','fastlapnum'))
tmp['fastlappc'] = round(100*tmp['fastlaptime']/min(tmp['fastlaptime'], na.rm=TRUE),1)
names(tmp) <- c("DRIVER", "FASTEST LAP (S)","LAP","PER CENT")
kable(tmp[,c("DRIVER", "FASTEST LAP (S)","PER CENT","LAP")],format='markdown', row.names = FALSE)
```


