---
title: "F1 Practice Report Generator"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rootdir = './reports'
outdir="practice"
dir.create(rootdir, showWarnings = FALSE)
dir.create(paste(rootdir, outdir, sep='/'), showWarnings = FALSE)


```


## Race meeting settings

```{r}
stub='esp'
year=2018
country='Spain'

```


## Report generation

The following function will render a report for a practice session.

```{r}
renderDoc = function(outfile) {
  basefile="practice_template.Rmd"
  rmarkdown::render(basefile,
                    params = list(psession = psession,
                                  stub=stub, outdir = outdir, rootdir=rootdir,
                                  year = year, country=country,
                                  laptimeFilePath = laptimeFilePath),
                    output_file = outfile 
                    )
}

```

```{r ploop_setup, message=FALSE}
#For each practice, generate the report

output_files = c('* Practice')

for (psession in c(1,2,3)) {
  #~/Dropbox/wranglingf1datawithr/f1djR/scraping/bah18_p3laptimes.csv
  #laptimeFilePath=paste0("~/Dropbox/various/",stub,"18_p",psession,"laptimes.csv")
  laptimeFilePath=paste0("~/Dropbox/wranglingf1datawithr/f1djR/scraping/",stub,"18_p",psession,"laptimes.csv")
  outfile = paste0('practice_report_p', psession, '.md')
  renderDoc(paste(rootdir,outdir,outfile,sep='/'))
   
  output_files = c(output_files, paste0('\n\t* [FP',psession, '](',
                                       paste(outdir,outfile,sep='/'), ')' ))
}

writeLines(output_files, paste0(rootdir,"/SUMMARY_practice.md"))
```

