---
title: "F1 Qualifying Report Generator"
output: html_document
---

```{r init, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rootdir='./reports'
outdir="quali"

dir.create(rootdir, showWarnings = FALSE)
dir.create(paste(rootdir, outdir, sep='/'), showWarnings = FALSE)

```

## Race meeting settings

```{r}
stub = 'esp'
year = 2018
round = 5
gp = "Spain"

override=c(0,1200,2500)

laptimeFilePath=paste0("~/Dropbox/various/",stub,"18_qualilaptimes.csv")
laptimeFilePath=paste0("~/Dropbox/wranglingf1datawithr/f1djR/scraping/",stub,"18_qualilaptimes.csv")
```

```{r}
# TO DO - pass in quali session cuml time cutoff / override
# Need to find a way to auto detect this?
```

## Report generation

The following function will render a report for qualifying.


```{r q_db_setup, echo = FALSE}
library(RMySQL)
ergastdb=dbConnect(MySQL(),user='root',password='f1',host='127.0.0.1',port=3399,dbname='ergastdb')

q=paste0('SELECT name AS TEAM, constructorRef AS constructorId FROM constructors c')
teams=dbGetQuery(ergastdb, q)
```



```{r q_api_calls}
library(knitr)
library(f1djR)

qlaps= read.csv(laptimeFilePath)
cutoff=c(15,10,2)


##Session classifications page
#xx=pageGrabber('http://www.fia.com/events/fia-formula-one-world-championship/season-2017/session-classifications-19')
qr=qualiResults.df(year,round)
qr=merge(qr,teams)
qr=quali_progression_ergast_tx(qr)
#qr=quali_progression_ergast_tx(ergastifyQualiClass(fiaSessionClassQualifyingTidy(fiaTableGrabber(xx,4))))


qlapsb=rawLap_augment_quali(qlaps,ignore.first = TRUE)
# TO DO - need to find a better way of setting gaps
qlapsb=qsessionOverride(qlapsb,override[1], override[2], override[3])
#qlapsb=qsessionOverride(qlapsb,0,1500,3000)
qlapsb=quali_purplePatch(qlapsb)
```


```{r}
output_files = c('*  Qualifying')

#Quali session result
outfile = 'quali_session_result.md'
rmarkdown::render('quali_result_template.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     qr=qr), output_file = paste(rootdir,outdir,outfile, sep='/'))
output_files = c(output_files, paste0('\n\t* [Session Result](', outdir, '/', outfile, ')' ))


#Quali progression
outfile = 'quali_progression.md'
rmarkdown::render('quali_template_child_progression.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     qr=qr), output_file = paste(rootdir,outdir,outfile,sep='/'))
output_files = c(output_files, paste0('\n\t* [Progression](', outdir, '/', outfile, ')' ))
```





```{r}


#Quali utilisation
outfile = 'quali_utilisation.md'
rmarkdown::render('quali_template_child_session_utilisation.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     qlapsb=qlapsb, override=override), 
       output_file = paste(rootdir,outdir,outfile,sep='/'))
output_files = c(output_files, paste0('\n\t* [Session Utilisation](', outdir, '/', outfile, ')' ))



#Quali cut-off evolution
outfile = 'quali_cutoff_evolution.md'
rmarkdown::render('quali_cutoff_evolution_template.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     qr=qr, qlapsb=qlapsb, override=override), output_file = paste(rootdir,outdir,outfile,sep='/'))
output_files = c(output_files, paste0('\n\t* [Cutoff Time Evolution](', outdir, '/', outfile, ')' ))


#Quali face-off 
outfile = 'quali_faceoff.md'
rmarkdown::render('quali_team_faceoff_template.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     round=round, year=year), output_file = paste(rootdir,outdir,outfile,sep='/'))
output_files = c(output_files, paste0('\n\t* [Team Qualifying Faceoff](', outdir, '/', outfile, ')' ))

writeLines(output_files, paste0(rootdir,'/SUMMARY_quali.md'))
```


