---
title: "Quali Progression template"
output:
  md_document:
    variant: gfm
    
params:
  session: 'quali'
  stub: 'generic'
  outdir: 'quali'
  rootdir: './reports'
  year: 2018
  qr: NA
---

```{r q_cp_setup, echo=FALSE}
library(knitr)
library(f1djR)

knitr::opts_chunk$set(warning = FALSE, message=FALSE, echo=FALSE)

rootdir = params$rootdir
outdir = params$outdir
stub = params$stub
year = params$year
qr = params$qr

options(knitr.kable.NA = '')
```

```{r q_pr_opts, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
opts_knit$set(base.dir = paste(rootdir, outdir, sep='/'))
knitr::opts_chunk$set(fig.path = paste0("images/f1_" ,year, "_", stub, "-"))


qrm=quali_progression_ergast_melt(qr)
```


Drivers progressed through the qualifying session as follows:

```{r quali_slopegraph}
promoter_ergastf1dj(core_qualifying_rank_slopegraph(qr,qrm,spacer=0.21,reverse=T))
```



```{r quali_time_slopegraph}
promoter(core_qualifying_time_slopegraph(qr,qrm,spacer=0.21))
```

```{r q_pr_1to2, results='asis'}

qsr=subset(qr, subset=(q1time<q2time))
 qsr['driverName']=factor(qsr[['driverName']])
 
 
cat(paste0(knit_child(text="## Q1 into Q2\n",quiet=TRUE),'\n'))

cat('The following teams did not make it through:\n')
tc=count(subset(qr, subset=(qspos>16)),'TEAM')
kable(tc, format='markdown',row.names = FALSE)

if (length(levels(qsr$driverName))==0) {
  cat(paste0(knit_child(text='* all drivers improved on their best laptime from the previous session',quiet=TRUE),'\n'))
}


for (t in tc$TEAM) { 
  if (tc[tc['TEAM']==t,'freq']==2) {
    text = "* neither `r t` made it through from Q1 to Q2"
    cat(paste0(knit_child(text=text,quiet=TRUE),'\n')) 
  }
}

for (name in levels(qsr$driverName)) {
  q1time=qsr[qsr['driverName']==name,][['q1time']]
  q2time =qsr[qsr['driverName']==name,][['q2time']]
  text='* `r name` failed to improve his time from Q1, recording `r q2time` compared to `r q1time` (`r q2time-q1time`s slower)'
  t=paste0(knit_child(text=text,quiet=TRUE),'\n')
  cat(text=t)
}
```

```{r q_pr_2to3 , results='asis'}
qsr=subset(qr, subset=(q2time<q3time))
qsr['driverName']=factor(qsr[['driverName']])
cat(paste0(knit_child(text="## Q2 into Q3\n",quiet=TRUE),'\n'))

```


```{r qpr_noprogess, results='asis'}

cat('The following teams did not make it through:\n')
tc=count(subset(qr, subset=((qspos>10) & (qspos<=16))),'TEAM')
kable(tc, format='markdown',row.names = FALSE)

if (length(levels(qsr$driverName))==0) {
  cat(paste0(knit_child(text='* all drivers improved on their best laptime from the previous session',quiet=TRUE),'\n'))
}

for (t in tc$TEAM) { 
  if (tc[tc['TEAM']==t,'freq']==2) {
    text = "* neither `r t` made it through from Q2 to Q3"
    cat(paste0(knit_child(text=text,quiet=TRUE),'\n')) 
  }
}

tc=count(subset(qr, subset=(qspos<=10)),'TEAM')
for (t in tc$TEAM) { 
  if (tc[tc['TEAM']==t,'freq']==2) {
    text = "* both `r t` cars made it through to Q3"
    cat(paste0(knit_child(text=text,quiet=TRUE),'\n')) 
  }
}

for (name in levels(qsr$driverName)) {
  text="* `r name` failed to improve his time from Q2, recording `r qsr[qsr['driverName']==name,][['q3time']]` compared to `r qsr[qsr['driverName']==name,][['q2time']]` (`r qsr[qsr['driverName']==name,][['q3time']]-qsr[qsr['driverName']==name,][['q2time']]`s slower)"
  cat(paste0(knit_child(text=text,quiet=TRUE),'\n')) 
}
```


