---
title: "Battlemaps template"
output:
  md_document:
    variant: gfm
    
params:
  session: 'race'
  stub: 'generic'
  outdir: 'race'
  rootdir: './reports'
  year: 2018
  country: 'generic'
  results: NA
  pitstops: NA
  plist: NA
---
```{r bm_opts, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
opts_knit$set(base.dir = paste(rootdir, outdir, sep='/'))
knitr::opts_chunk$set(fig.path = paste0("images/f1_" ,year, "_", stub, "-"))

```

```{r bm_setup}
library(f1djR)

session = params$session
rootdir = params$rootdir
outdir = params$outdir
stub = params$stub
year = params$year
country = params$country
plist = params$plist
```

## Race Battlemaps
```{r bm_template}
template=c(paste0("```{r battlemap_",year,"_",country,"_{{code}}}"),
           paste0("promoter(battlemapFull_byDriver(lapTimes,'{{code}}','", year, ' ', country, " - {{code}} Battlemap',c(-20,20)))"),
           '```')

#The list needs to be sorted in race finish order

#This shows factors for code as factor??
#results['code']$code),unique(lapTimes['code'])$code)
#c('HAM','VET', 'VES','RIC','RAI','BOT')
src = lapply(plist, function(code) knit_expand(text=c(template)))
```

`r knit(text = unlist(src))`
