---
title: "F1 Story So Far Template"
output:
  md_document:
    variant: gfm
params:
  circuitref: 'bahrain'
  round: 2
  year: 2018
  name: 'XXX'
  country: 'YYY'
  location: 'ZZZ'
  stub: 'generic'
  outdir: 'storysofar'
  rootdir: './reports'

---

```{r setup_ssf_circuit_rank, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```
# Circuit Winner

How well a driver does at a circuit

```{r}

circuitref = params$circuitref
round = params$round
year = params$year
name = params$name
country = params$country
location = params$location

library(RMySQL)
ergastdb=dbConnect(MySQL(),user='root',password='f1',host='127.0.0.1',port=3399,dbname='ergastdb')
```



```{r driver_circuit_performance}
library(plyr)

q=paste0('SELECT driverRef, code, MAX(year) as until,SUM(11-position) s FROM races r JOIN circuits c JOIN results rs JOIN drivers d WHERE r.circuitId=c.circuitId AND r.raceId=rs.raceId AND position<=10 AND d.driverID=rs.driverId AND circuitref="',circuitref,'" GROUP BY driverRef, code  DESC ORDER BY s DESC LIMIT 10')
leaders = dbGetQuery(ergastdb, q)

q=paste0('SELECT year, driverRef, code, position FROM races r JOIN circuits c JOIN results rs JOIN drivers d WHERE r.circuitId=c.circuitId AND r.raceId=rs.raceId AND position<=10 AND d.driverID=rs.driverId AND circuitref="',circuitref,'" ORDER BY year')
 #The dbGetQuery() function is provided by the DBI library
res = dbGetQuery(ergastdb, q)

res$pts = 11-res$position
res = ddply(res, .(driverRef), transform, totPts=cumsum(pts)  )


library(ggplot2)
library(directlabels)
library(ggrepel)
library(ggthemes)

g=ggplot(data=res[res$code %in% leaders$code,], aes(x=year, y=totPts))+ geom_step(aes(col=code))
g=g+geom_point(data=res[(res$position <=3) & (res$code %in% leaders$code),],aes( size=factor(position),shape=factor(position),col=code)) + scale_size_manual(values=c(2,1.2,0.8)) + scale_shape_manual(values=c(2,6,1))



g=g+ geom_line(data=res[!(res$code %in% leaders$code),], aes(group=driverRef),col='grey')

#Label the lines
g=g+geom_label_repel(data=leaders,aes(x=until, y=s,label = code), na.rm = TRUE, arrow = arrow(length = unit(0.01, 'npc')), nudge_y =3, nudge_x =2, segment.size = 0.2,size=2)

g=g + guides(color=FALSE)+xlim(round_any(min(res$year)-1.5,5),2025)+ylim(0,110)+theme_bw()+ggtitle(paste0('F1 ',country,' - ',name,', ',location ,' - Driver Performance, ',min(res$year),' to ',max(res$year)))

g = g+ylab('Total "Points"')+xlab(NULL)
g + guides(size=FALSE, shape=FALSE)
```
