---
title: "F1 Story So Far Template"
output:
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
library(knitr)
library(f1djR)
library(toOrdinal)
library(plyr)

rootdir = './reports'
outdir="preview"

dir.create(rootdir, showWarnings = FALSE)
dir.create(paste(rootdir, outdir, sep='/'), showWarnings = FALSE)

round= 5
stub= 'esp'

year= 2018


knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

```

## The Story So Far


```{r race_db_setup, echo = FALSE}
library(RMySQL)
ergastdb=dbConnect(MySQL(),user='root',password='f1',host='127.0.0.1',port=3399,dbname='ergastdb')
```

```{r}
q=paste0('SELECT code FROM drivers d JOIN races r JOIN results rs WHERE d.driverId=rs.driverId AND r.raceId=rs.raceId AND year=',year)
driversThisYear= as.list(dbGetQuery(ergastdb, q))$code
driversThisYear_str = paste("'",driversThisYear,"'", collapse=',', sep='')
```

```{r}
q=paste0('SELECT c.name FROM constructors c JOIN races r JOIN results rs WHERE c.constructorId=rs.constructorId AND r.raceId=rs.raceId AND year=',year)
teamsThisYear= as.list(dbGetQuery(ergastdb, q))$name
teamsThisYear_str = paste("'",teamsThisYear,"'", collapse=',', sep='')
```

```{r}
#driverteamsthisyear
q_driverteamsthisyear=paste0('SELECT c.name name, d.code code FROM constructors c JOIN races r JOIN results rs JOIN drivers d WHERE c.constructorId=rs.constructorId AND r.raceId=rs.raceId and d.driverId=rs.driverId AND r.year=',year)
#dbGetQuery(ergastdb, q_driverteamsthisyear)
```



```{r}
library(ggplot2)
library(directlabels)
championship_race_charter=function(g) {
  #Generate a line chart
  g = g + geom_line()
  #Remove axis labels and colour legend
  g = g + ylab(NULL) + xlab(NULL) + guides(color=FALSE)
  #Add a title
  g = g + ggtitle("F1 Drivers' Championship Race, 2018")
  #Add right hand side padding to the chart so the labels don't overflow
  g + scale_x_continuous(limits=c(1,22), breaks=c(5,10,15))
}
```




```{r}
library(plyr)
library(ggplot2)
library(directlabels)
library(ggrepel)
library(ggthemes)
library(reshape2)
```


```{r cct_champChartTheme}

champChartTheme=function(g){
  g = g + theme_minimal(base_family="Arial Narrow")
  #g = g + theme(panel.grid.major.y=element_blank())
  g = g + theme(panel.grid.minor=element_blank())
  g = g + theme(axis.line.y=element_line(color="#2b2b2b", size=0.15))
  g = g + theme(axis.text.y=element_text(margin=margin(r=0, l=0)))
  g = g + theme(plot.margin=unit(rep(30, 4), "pt"))
  g = g + theme(plot.title=element_text(face="bold"))
  g = g + theme(plot.subtitle=element_text(margin=margin(b=10)))
  g = g + theme(plot.caption=element_text(size=8, margin=margin(t=10)))
  g
}
```

```{r cctdetails}
q=paste0('SELECT circuitRef, c.name AS circuit, r.name as race, location, country FROM races r JOIN circuits c WHERE r.circuitId=c.circuitId AND year=',year,' AND round=',round)
cct = as.list(dbGetQuery(ergastdb, q))
```


```{r ssf_histlaptime}

output_files = c('* Story So Far')

knitr::opts_chunk$set(fig.path = paste0(rootdir,'/',outdir,
                                        "/images/f1_" ,year, "_", stub, "-"))

#Event Trivia
outfile ='story_so_far_trivia.md'
rmarkdown::render('ssf_trivia_template.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     year = year, ergastdb=ergastdb,
                     round=round, q_driverteamsthisyear=q_driverteamsthisyear,
                     driversThisYear_str=driversThisYear_str), output_file = paste(rootdir,outdir,outfile, sep='/'), encoding = 'UTF-8')
output_files = c(output_files, paste0("\n\t* [Event Trivia](", outdir, '/', outfile, ')' ))


#Championship Standings
outfile ='story_so_far_standings.md'
rmarkdown::render('ssf_championship_standings_template.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     year = year, ergastdb=ergastdb,
                     round=round), output_file = paste(rootdir,outdir,outfile, sep='/'))
output_files = c(output_files, paste0("\n\t* [Championship Standings](", outdir, '/', outfile, ')' ))


#Historical Laptimes and Competitive Supertimes
outfile ='story_so_far_laptimes.md'
rmarkdown::render('ssf_competitive_laptime_template.Rmd',
       params = list(stub=stub, year=year,  outdir = outdir, rootdir=rootdir,
                     cct = cct, ergastdb=ergastdb,
                     teamsThisYear_str=teamsThisYear_str), output_file = paste(rootdir,outdir,outfile, sep='/'))
output_files = c(output_files, paste0("\n\t* [Drivers' & Constructors'  Historical Laptimes and Competitive Supertimes](", outdir, '/', outfile, ')' ))

#Circuit Performance
outfile = 'story_so_far_circuit_performance.md'
rmarkdown::render('ssf_circuit_performance_template.Rmd',
       params = list(stub=stub, outdir = outdir, rootdir=rootdir,
                     cct = cct, ergastdb=ergastdb, year=year,
                     teamsThisYear_str=teamsThisYear_str), output_file = paste(rootdir,outdir,outfile,sep='/'))
output_files = c(output_files, paste0("\n\t* [Circuit Performance](", outdir, '/', outfile, ')' ))


writeLines(output_files, paste0(rootdir,'/SUMMARY_leadup.md'))
```
